### ISSUE TITLE
Setup the webapp

### ISSUE THREAD

**Issue by Neptuneee11** [Neptuneee11/CSCI42-project_Rainbow6#11]
# Overview
Everyone knows how to set up a Django webapp here but we may have different versions. So, we need a consistent virtual environment to work on.
# Output requirements
- [x] requirements.txt for the virtual environment
- [x] include Django FSM
- [x] cheatsheet of all the django terminal commands (QOL)

**Comment by Neptuneee11** [comment]
This Pull Request merged it into main #16. 

I just need the `requirements.txt` for the venv that will run this

**Comment by Neptuneee11** [comment]
#19 Means that task 1 is done

**Comment by Aec110** [comment]
Task 3: https://dev.to/ericchapman/my-beloved-django-cheat-sheet-2056

**Comment by Neptuneee11** [comment]
#21 is task 2 done.

nice
