### ISSUE TITLE
Databases for bikes, transactions, and user info.

### ISSUE THREAD

**Issue by kenkaster001** [Neptuneee11/CSCI42-project_Rainbow6#14]
creating the tables

**Comment by kenkaster001** [comment]
![image](https://github.com/Neptuneee11/CSCI42-project_Rainbow6/assets/63447994/f49c5199-4fe7-447f-8ff4-0ee22fc5960b)

 
(updated) ERD for ABRA 
Authentication Primary Key was made to be both Customer_ID and Password

**Comment by kenkaster001** [comment]
creating the data dictionary

link: https://docs.google.com/document/d/12Jvjj5m_3Z7EFIWr9e4n0RovSXm42F2P9uasqA-KfAw/edit?usp=sharing

**Comment by kenkaster001** [comment]
mysql table sample (will still test by adding sample data to check if the foreign keys work as intended)

(image of tables in mysql)

![image](https://github.com/Neptuneee11/CSCI42-project_Rainbow6/assets/63447994/9b21e478-cc5c-4263-accf-ea0a49871292)

**Comment by Neptuneee11** [comment]
> creating the data dictionary
> 
> link: https://docs.google.com/document/d/12Jvjj5m_3Z7EFIWr9e4n0RovSXm42F2P9uasqA-KfAw/edit?usp=sharing

@N03L9 @JoaquinHermosisima Help him out here.

**Comment by Neptuneee11** [comment]
ERD's are done. New expansions will be for a new issue
