### ISSUE TITLE
Geolocation in Django

### ISSUE THREAD

**Issue by Neptuneee11** [Neptuneee11/CSCI42-project_Rainbow6#23]
# Overview
Get the webapp to know  your location when you ping it.
# Requirements
This should be done in a django app
- [x] prompt asking user for permission
- [x] return text of location everytime a button is pressed
  - [x] button
  - [x] textField

**Comment by Aec110** [comment]
ive added the latitude and longitude values of your geolocation in the latest version of the branch

**Comment by Aec110** [comment]
of the users' geolocation*
